---
- name: Install libfreetype6-dev for matplotlib
  apt: pkg=libfreetype6-dev state=installed update_cache=true

- name: Install pkg-config for matplotlib
  apt: pkg=pkg-config state=installed update_cache=true

- name: install matplotlib
  pip: name=matplotlib state=present executable=pip3

- name: install statsmodels for seaborn
  pip: name=statsmodels state=present executable=pip3

- name: install seaborn
  pip: name=seaborn state=present executable=pip3

- name: install bqplot
  pip: name=bqplot state=present executable=pip3

- name: install bokeh (version 0.12.3 needed for holoviews")
  pip: name=bokeh state=present version="0.12.3" executable=pip3

- name: install holoviews
  pip: name="holoviews[recommended]" state=present executable=pip3

- name: install cloudpickle (required for holoviews)
  pip: name=cloudpickle state=present executable=pip3

- name: install cython
  pip: name=cython state=present executable=pip3
