---
- name: Install libfreetype6-dev for matplotlib
  apt: pkg=libfreetype6-dev state=installed update_cache=true

- name: Install pkg-config for matplotlib
  apt: pkg=pkg-config state=installed update_cache=true

- name: install matplotlib
  pip: name=matplotlib state=present executable=pip3

- name: install statsmodels for seaborn
  pip: name=statsmodels state=present executable=pip3

- name: install seaborn
  pip: name=seaborn state=present executable=pip3

- name: install bqplot
  pip: name=bqplot state=present executable=pip3

- name: install bokeh
  pip: name=bokeh state=present executable=pip3

- name: install holoviews
  pip: name=holoviews state=present executable=pip3
